[2023-12-01T00:43:13.674+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-12-01T00:43:09.112331+00:00 [queued]>
[2023-12-01T00:43:13.694+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-12-01T00:43:09.112331+00:00 [queued]>
[2023-12-01T00:43:13.695+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-01T00:43:13.762+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): extract_data_from_csv> on 2023-12-01 00:43:09.112331+00:00
[2023-12-01T00:43:13.805+0000] {standard_task_runner.py:57} INFO - Started process 2632 to run task
[2023-12-01T00:43:13.817+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'extract_data_from_csv', 'manual__2023-12-01T00:43:09.112331+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmpmqlv16xy']
[2023-12-01T00:43:13.819+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask extract_data_from_csv
[2023-12-01T00:43:14.034+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-12-01T00:43:09.112331+00:00 [running]> on host 227737b5950b
[2023-12-01T00:43:14.258+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chibuikeokenu@gmail.com' AIRFLOW_CTX_DAG_OWNER='Golstine' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='extract_data_from_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:43:09.112331+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-01T00:43:09.112331+00:00'
[2023-12-01T00:43:14.259+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-01T00:43:14.261+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cut -d","  -f1,2,3,4 /opt/***/files/vehicle-data.csv > /opt/***/files/csv_data.csv']
[2023-12-01T00:43:14.295+0000] {subprocess.py:86} INFO - Output:
[2023-12-01T00:43:14.301+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /opt/***/files/csv_data.csv: No such file or directory
[2023-12-01T00:43:14.305+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-01T00:43:14.330+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-01T00:43:14.338+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_toll_data, task_id=extract_data_from_csv, execution_date=20231201T004309, start_date=20231201T004313, end_date=20231201T004314
[2023-12-01T00:43:14.366+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task extract_data_from_csv (Bash command failed. The command returned a non-zero exit code 1.; 2632)
[2023-12-01T00:43:14.444+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T00:43:14.566+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
