[2023-12-01T00:35:22.900+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T00:30:18.983667+00:00 [queued]>
[2023-12-01T00:35:22.916+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T00:30:18.983667+00:00 [queued]>
[2023-12-01T00:35:22.916+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-01T00:35:22.938+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): unzip_data> on 2023-12-01 00:30:18.983667+00:00
[2023-12-01T00:35:22.949+0000] {standard_task_runner.py:57} INFO - Started process 2509 to run task
[2023-12-01T00:35:22.953+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'unzip_data', 'manual__2023-12-01T00:30:18.983667+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmp79e14zub']
[2023-12-01T00:35:22.955+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask unzip_data
[2023-12-01T00:35:23.041+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T00:30:18.983667+00:00 [running]> on host 227737b5950b
[2023-12-01T00:35:23.166+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chibuikeokenu@gmail.com' AIRFLOW_CTX_DAG_OWNER='Golstine' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='unzip_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:30:18.983667+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-01T00:30:18.983667+00:00'
[2023-12-01T00:35:23.168+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-01T00:35:23.168+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'ls -l /opt/***/files/tolldata.tgz']
[2023-12-01T00:35:23.197+0000] {subprocess.py:86} INFO - Output:
[2023-12-01T00:35:23.206+0000] {subprocess.py:93} INFO - ls: cannot access '/opt/***/files/tolldata.tgz': No such file or directory
[2023-12-01T00:35:23.207+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-01T00:35:23.227+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-01T00:35:23.232+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ETL_toll_data, task_id=unzip_data, execution_date=20231201T003018, start_date=20231201T003522, end_date=20231201T003523
[2023-12-01T00:35:23.253+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task unzip_data (Bash command failed. The command returned a non-zero exit code 2.; 2509)
[2023-12-01T00:35:23.268+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T00:35:23.316+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
