[2023-12-01T00:30:20.829+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T00:30:18.983667+00:00 [queued]>
[2023-12-01T00:30:20.886+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T00:30:18.983667+00:00 [queued]>
[2023-12-01T00:30:20.886+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-01T00:30:20.978+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): unzip_data> on 2023-12-01 00:30:18.983667+00:00
[2023-12-01T00:30:21.001+0000] {standard_task_runner.py:57} INFO - Started process 2436 to run task
[2023-12-01T00:30:21.026+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'unzip_data', 'manual__2023-12-01T00:30:18.983667+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmpyt_6_qse']
[2023-12-01T00:30:21.030+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask unzip_data
[2023-12-01T00:30:21.227+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T00:30:18.983667+00:00 [running]> on host 227737b5950b
[2023-12-01T00:30:21.477+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chibuikeokenu@gmail.com' AIRFLOW_CTX_DAG_OWNER='Golstine' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='unzip_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:30:18.983667+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-01T00:30:18.983667+00:00'
[2023-12-01T00:30:21.484+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-01T00:30:21.486+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'ls -l /opt/***/files/tolldata.tgz']
[2023-12-01T00:30:21.540+0000] {subprocess.py:86} INFO - Output:
[2023-12-01T00:30:21.570+0000] {subprocess.py:93} INFO - ls: cannot access '/opt/***/files/tolldata.tgz': No such file or directory
[2023-12-01T00:30:21.571+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-01T00:30:21.597+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-01T00:30:21.610+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_toll_data, task_id=unzip_data, execution_date=20231201T003018, start_date=20231201T003020, end_date=20231201T003021
[2023-12-01T00:30:21.641+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task unzip_data (Bash command failed. The command returned a non-zero exit code 2.; 2436)
[2023-12-01T00:30:21.714+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T00:30:21.767+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
