[2023-11-30T22:32:23.438+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-11-30T22:32:09.576487+00:00 [queued]>
[2023-11-30T22:32:23.651+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-11-30T22:32:09.576487+00:00 [queued]>
[2023-11-30T22:32:23.651+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-30T22:32:23.802+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): unzip_data> on 2023-11-30 22:32:09.576487+00:00
[2023-11-30T22:32:23.820+0000] {standard_task_runner.py:57} INFO - Started process 887 to run task
[2023-11-30T22:32:23.829+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'unzip_data', 'manual__2023-11-30T22:32:09.576487+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmpnv5lgzhx']
[2023-11-30T22:32:23.833+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask unzip_data
[2023-11-30T22:32:24.124+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_toll_data.unzip_data manual__2023-11-30T22:32:09.576487+00:00 [running]> on host 227737b5950b
[2023-11-30T22:32:24.748+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chibuikeokenu@gmail.com' AIRFLOW_CTX_DAG_OWNER='Golstine' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='unzip_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T22:32:09.576487+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T22:32:09.576487+00:00'
[2023-11-30T22:32:24.795+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T22:32:24.820+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'tar xzf /home/datang/***/logs/tolldata.tgz']
[2023-11-30T22:32:24.866+0000] {subprocess.py:86} INFO - Output:
[2023-11-30T22:32:24.925+0000] {subprocess.py:93} INFO - tar (child): /home/datang/***/logs/tolldata.tgz: Cannot open: No such file or directory
[2023-11-30T22:32:24.926+0000] {subprocess.py:93} INFO - tar (child): Error is not recoverable: exiting now
[2023-11-30T22:32:24.929+0000] {subprocess.py:93} INFO - tar: Child returned status 2
[2023-11-30T22:32:24.930+0000] {subprocess.py:93} INFO - tar: Error is not recoverable: exiting now
[2023-11-30T22:32:24.939+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-30T22:32:25.014+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-30T22:32:25.050+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_toll_data, task_id=unzip_data, execution_date=20231130T223209, start_date=20231130T223223, end_date=20231130T223225
[2023-11-30T22:32:25.148+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task unzip_data (Bash command failed. The command returned a non-zero exit code 2.; 887)
[2023-11-30T22:32:25.444+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T22:32:25.596+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
