[2023-12-01T21:32:37.671+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T21:32:35.631399+00:00 [queued]>
[2023-12-01T21:32:37.686+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T21:32:35.631399+00:00 [queued]>
[2023-12-01T21:32:37.687+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-01T21:32:37.733+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): unzip_data> on 2023-12-01 21:32:35.631399+00:00
[2023-12-01T21:32:37.765+0000] {standard_task_runner.py:57} INFO - Started process 17961 to run task
[2023-12-01T21:32:37.770+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'unzip_data', 'manual__2023-12-01T21:32:35.631399+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmpe043_e6x']
[2023-12-01T21:32:37.772+0000] {standard_task_runner.py:85} INFO - Job 109: Subtask unzip_data
[2023-12-01T21:32:38.034+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T21:32:35.631399+00:00 [running]> on host 227737b5950b
[2023-12-01T21:32:38.324+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chibuikeokenu@gmail.com' AIRFLOW_CTX_DAG_OWNER='Golstine' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='unzip_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T21:32:35.631399+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-01T21:32:35.631399+00:00'
[2023-12-01T21:32:38.325+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-01T21:32:38.326+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'tar -xzf /opt/***/logs/tolldata.tgz/']
[2023-12-01T21:32:38.371+0000] {subprocess.py:86} INFO - Output:
[2023-12-01T21:32:38.387+0000] {subprocess.py:93} INFO - tar (child): /opt/***/logs/tolldata.tgz/: Cannot open: Not a directory
[2023-12-01T21:32:38.388+0000] {subprocess.py:93} INFO - tar (child): Error is not recoverable: exiting now
[2023-12-01T21:32:38.393+0000] {subprocess.py:93} INFO - 
[2023-12-01T21:32:38.393+0000] {subprocess.py:93} INFO - gzip: stdin: unexpected end of file
[2023-12-01T21:32:38.394+0000] {subprocess.py:93} INFO - tar: Child returned status 2
[2023-12-01T21:32:38.395+0000] {subprocess.py:93} INFO - tar: Error is not recoverable: exiting now
[2023-12-01T21:32:38.395+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-01T21:32:38.417+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-01T21:32:38.434+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_toll_data, task_id=unzip_data, execution_date=20231201T213235, start_date=20231201T213237, end_date=20231201T213238
[2023-12-01T21:32:38.477+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 109 for task unzip_data (Bash command failed. The command returned a non-zero exit code 2.; 17961)
[2023-12-01T21:32:38.532+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T21:32:38.628+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
