[2023-11-30T22:23:11.330+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-11-30T22:19:16.258277+00:00 [queued]>
[2023-11-30T22:23:11.372+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-11-30T22:19:16.258277+00:00 [queued]>
[2023-11-30T22:23:11.372+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2023-11-30T22:23:11.416+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): unzip_data> on 2023-11-30 22:19:16.258277+00:00
[2023-11-30T22:23:11.434+0000] {standard_task_runner.py:57} INFO - Started process 744 to run task
[2023-11-30T22:23:11.447+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'unzip_data', 'manual__2023-11-30T22:19:16.258277+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmpz8vfh6x3']
[2023-11-30T22:23:11.452+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask unzip_data
[2023-11-30T22:23:11.672+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_toll_data.unzip_data manual__2023-11-30T22:19:16.258277+00:00 [running]> on host 227737b5950b
[2023-11-30T22:23:12.018+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chibuikeokenu@gmail.com' AIRFLOW_CTX_DAG_OWNER='Golstine' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='unzip_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T22:19:16.258277+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T22:19:16.258277+00:00'
[2023-11-30T22:23:12.020+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T22:23:12.020+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'tar xzf /home/datang/***/dags/tolldata.tgz']
[2023-11-30T22:23:12.195+0000] {subprocess.py:86} INFO - Output:
[2023-11-30T22:23:12.292+0000] {subprocess.py:93} INFO - tar (child): /home/datang/***/dags/tolldata.tgz: Cannot open: No such file or directory
[2023-11-30T22:23:12.293+0000] {subprocess.py:93} INFO - tar (child): Error is not recoverable: exiting now
[2023-11-30T22:23:12.295+0000] {subprocess.py:93} INFO - tar: Child returned status 2
[2023-11-30T22:23:12.295+0000] {subprocess.py:93} INFO - tar: Error is not recoverable: exiting now
[2023-11-30T22:23:12.296+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-30T22:23:12.396+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-30T22:23:12.427+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_toll_data, task_id=unzip_data, execution_date=20231130T221916, start_date=20231130T222311, end_date=20231130T222312
[2023-11-30T22:23:12.578+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task unzip_data (Bash command failed. The command returned a non-zero exit code 2.; 744)
[2023-11-30T22:23:12.613+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T22:23:12.867+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
