[2023-12-01T00:28:03.645+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T00:22:52.222158+00:00 [queued]>
[2023-12-01T00:28:03.666+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T00:22:52.222158+00:00 [queued]>
[2023-12-01T00:28:03.666+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-01T00:28:03.688+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): unzip_data> on 2023-12-01 00:22:52.222158+00:00
[2023-12-01T00:28:03.706+0000] {standard_task_runner.py:57} INFO - Started process 2400 to run task
[2023-12-01T00:28:03.712+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'unzip_data', 'manual__2023-12-01T00:22:52.222158+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmpv_08l2nz']
[2023-12-01T00:28:03.715+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask unzip_data
[2023-12-01T00:28:03.852+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_toll_data.unzip_data manual__2023-12-01T00:22:52.222158+00:00 [running]> on host 227737b5950b
[2023-12-01T00:28:04.057+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chibuikeokenu@gmail.com' AIRFLOW_CTX_DAG_OWNER='Golstine' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='unzip_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:22:52.222158+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-01T00:22:52.222158+00:00'
[2023-12-01T00:28:04.059+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-01T00:28:04.066+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'tar xzf /opt/***/files/tolldata.tgz']
[2023-12-01T00:28:04.117+0000] {subprocess.py:86} INFO - Output:
[2023-12-01T00:28:04.138+0000] {subprocess.py:93} INFO - tar (child): /opt/***/files/tolldata.tgz: Cannot open: No such file or directory
[2023-12-01T00:28:04.138+0000] {subprocess.py:93} INFO - tar (child): Error is not recoverable: exiting now
[2023-12-01T00:28:04.141+0000] {subprocess.py:93} INFO - tar: Child returned status 2
[2023-12-01T00:28:04.141+0000] {subprocess.py:93} INFO - tar: Error is not recoverable: exiting now
[2023-12-01T00:28:04.142+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-01T00:28:04.171+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-01T00:28:04.179+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ETL_toll_data, task_id=unzip_data, execution_date=20231201T002252, start_date=20231201T002803, end_date=20231201T002804
[2023-12-01T00:28:04.210+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task unzip_data (Bash command failed. The command returned a non-zero exit code 2.; 2400)
[2023-12-01T00:28:04.232+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T00:28:04.281+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
